---
- hosts: node
  remote_user: ansible
  become: true
  tasks:
  - name: "Install Package"
    yum:
     name: httpd
     state: latest
  - name: Start service httpd and enable
    service:
     name: httpd
     state: started
     enabled: yes
  - name: Create index file
    file:
     path: /var/www/html/index.html
     state: touch
  - name: Add content to the file
    lineinfile:
     path: /var/www/html/index.html
     line: Hello World
  - name: Install firewall
    yum:
     name: firewalld
     state: latest
  - name: Start and enable firewalld
    service:
     name: firewalld
     state: started
     enabled: yes
  - name: Add port 80 to firewall
    firewalld:
     port: 80/tcp
     permanent: true
     state: enabled
  - name: Reload firewalld
    service:
     name: firewalld
     state: reloaded